### ISSUE TITLE
As a Logsearch user, I want to analyze all my AWS logs so that I can get on top of my account

### ISSUE THREAD

**Issue by sopel** [logsearch/logsearch-for-aws#1]
This epic basically resembles the raison d'être for this project/repository. It will be broken down into separate stories per specific use case resp. AWS log type and mainly serves as a wrapper for gathering information until more appropriate contexts are available.

**Comment by sopel** [comment]
## Use cases

The following use cases have been identified so far:

### Logs

Log data usually needs to be read from S3 buckets, either by polling, or preferably after receiving a log delivery push notification (meanwhile available as a generic S3 object creation notification).
- [x] As an AWS user, I want to analyze [AWS CloudTrail](http://aws.amazon.com/cloudtrail/) logs so that I can reason about my account's security
  - see #2 for details
  - see also https://github.com/cityindex-attic/logsearch/issues/227 for a previous version of this story
- [ ] As an AWS user, I want to analyze [AWS Config](http://aws.amazon.com/config/) logs so that I can reason about my account's resource footprint/evolution
  - see #6 for details
- [ ] As an AWS user, I want to analyze [AWS CloudFront](http://aws.amazon.com/cloudfront/) logs so that I can reason about my distribution's effectiveness
  - :information_source: AWS CloudFront finally offers built in dashboards for this as of recently, see [CloudFront Update – Trends, Metrics, Charts, More Timely Logs](https://aws.amazon.com/blogs/aws/cloudfront-up-trends-metrics-stats/) - however, this doesn't undermine the value of having the data available alongside other operational events for correlation etc.
- [x] As an AWS user, I want to analyze [Amazon S3](http://aws.amazon.com/s3/) logs so that I can reason about my bucket's usage
  - see #7 for details
- [ ] As an AWS user, I want to analyze [Amazon RDS](http://aws.amazon.com/cloudtrail/) logs so that I can reason about my database's performance
- [ ] As an AWS user, I want to analyze [Amazon CloudWatch](http://aws.amazon.com/cloudwatch/) logs so that I can analyze arbitrary logs in turn
  - see also https://github.com/cityindex-attic/logsearch/issues/226 for a previous version of this story
- [x] As an AWS user, I want to analyze [AWS Account Billing](http://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/detailed-billing-reports.html) logs so that I can correlate cost with operational metrics
  - :interrobang: The resp. log formats are fairly complex and granular, so this is likely out of scope for the time being?!
- [ ] As an AWS user, I want to analyze [Elastic Load Balancing Access Logs](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/access-log-collection.html)
- [ ] As an AWS user, I want to analyze [VPC Flow Logs](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/flow-logs.html) so that I can reason about my account's network traffic

### Events

Events generate push notifications, but the common and preferred pattern for consuming them reliably is subscribing an [Amazon SQS](http://aws.amazon.com/sqs/) queue to a SNS topic and consuming SQS messages in turn, see Queues/Streams below
- [ ] As an AWS user, I want to monitor [Amazon SNS](http://aws.amazon.com/sns/) notifications so that I can correlate arbitrary events with operational logs and metrics
  - see also https://github.com/cityindex-attic/logsearch/issues/245 for a previous version of this story
  - :exclamation: **This is likely the super set of all more specific ones based on SNS** down below, though these would likely still be differentiated regarding data mapping and dashboard composition etc.!
- [ ] As an AWS user, I want to analyze [Auto Scaling](http://aws.amazon.com/autoscaling/) notifications so that I can correlate resource lifecycle events with operational metrics
- [ ] As an AWS user, I want to analyze [AWS CloudFormation](http://aws.amazon.com/cloudformation/) notifications so that I can correlate resource lifecycle events with operational metrics
- [ ] As an AWS user, I want to analyze [Amazon S3](http://aws.amazon.com/s3/) notifications so that I can correlate resource lifecycle events with operational metrics

## Queues/Streams

Queues/Streams usually need to be polled by workers that are auto scaling based on queue/stream metrics.
- [ ] As an AWS user, I want to ingest [Amazon SQS](http://aws.amazon.com/sqs/) messages from SQS queues so that I can analyze arbitrary messages
- [ ] As an AWS user, I want to ingest [Amazon Kinesis](http://aws.amazon.com/kinesis/) events from Kinesis streams so that I can analyze arbitrary events
- [ ] As an AWS user, I want to ingest [Amazon DynamoDB](http://aws.amazon.com/dynamodb/) events from DynamoDB streams so that I can correlate resource lifecycle events with operational metrics
  - :exclamation: **This is going to be pretty much the same as ingesting Kinesis event streams**, insofar AWS has sufficiently aligned the resp. formats to be handled by a single library/solution.
  - :exclamation: Also worth noting that AWS has stated the goal of converging to only a few schemata for this purpose.

**Comment by sopel** [comment]
## Log formats

The following log formats have been identified so far:

### JSON

Most logs and events are facilitating JSON these days, and AWS has stated that they aim to converge to only a few schemata for this purpose.

### CSV

Some logs like e.g. Amazon CloudFront and Amazon S3 are facilitating the common structured web server log formats. The AWS Account Billing Data is logged in CSV.

**Comment by dpb587** [comment]
Billing Logs started in 8c96bb76
